/* eslint-disable @next/next/no-img-element */

import { ImageResponse } from "next/og";
import fs from "fs";
import path from "path";
import type { SocialJob } from "./types";

const NAVY = "#173B78";
const RED = "#F21D25";
const LIGHT_BLUE = "#EAF3FF";
const BORDER = "#B9C9DE";

/**
 * Read the local illustration from /public/images
 * and convert it to a data URL.
 *
 * ImageResponse/Satori cannot use the relative
 * Next.js static asset URL generated by:
 *
 * import image from ".../illustrate.png"
 *
 * Therefore we embed the image directly as Base64.
 */
function getIllustrationDataUrl() {
  const imagePath = path.join(
    process.cwd(),
    "public",
    "images",
    "illustrate.png",
  );

  if (!fs.existsSync(imagePath)) {
    throw new Error(
      `Illustration image not found: ${imagePath}`,
    );
  }

  const imageBuffer = fs.readFileSync(imagePath);

  return `data:image/png;base64,${imageBuffer.toString(
    "base64",
  )}`;
}

function truncate(
  value: string | null | undefined,
  max: number,
) {
  if (!value) return "";

  return value.length <= max
    ? value
    : `${value
        .slice(0, max - 1)
        .trim()}…`;
}

function getLocation(job: SocialJob) {
  return [
    job.city,
    job.state,
    job.country,
  ]
    .filter(Boolean)
    .join(", ");
}

function getSkills(job: SocialJob) {
  if (!job.requiredSkills) return [];

  return job.requiredSkills
    .split(/[,|]/)
    .map((skill) => skill.trim())
    .filter(Boolean)
    .slice(0, 5);
}

function getExperience(job: SocialJob) {
  return (
    job.experienceLevel?.trim() ||
    "Experienced"
  );
}

/* ========================================= */
/* LOCATION ICON                             */
/* ========================================= */

function LocationIcon() {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 24 24"
    >
      <path
        d="M12 21s7-6.2 7-12A7 7 0 1 0 5 9c0 5.8 7 12 7 12Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.2"
      />

      <circle
        cx="12"
        cy="9"
        r="2.4"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}

/* ========================================= */
/* BRIEFCASE ICON                            */
/* ========================================= */

function BriefcaseIcon() {
  return (
    <svg
      width="31"
      height="31"
      viewBox="0 0 24 24"
    >
      <rect
        x="4"
        y="6.5"
        width="16"
        height="12.5"
        rx="2"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />

      <path
        d="M9 6.5V4h6v2.5M4 11h16"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}

/* ========================================= */
/* EYE ICON                                  */
/* ========================================= */

function EyeIcon() {
  return (
    <svg
      width="30"
      height="30"
      viewBox="0 0 24 24"
    >
      <path
        d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />

      <circle
        cx="12"
        cy="12"
        r="2.7"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
      />
    </svg>
  );
}

/* ========================================= */
/* ARROW ICON                                */
/* ========================================= */

function ArrowIcon() {
  return (
    <svg
      width="31"
      height="31"
      viewBox="0 0 24 24"
    >
      <path
        d="M4 12h15M13 6l6 6-6 6"
        fill="none"
        stroke="currentColor"
        strokeWidth="2.2"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

/* ========================================= */
/* INSTAGRAM ICON                            */
/* ========================================= */

function InstagramIcon() {
  return (
    <svg
      width="54"
      height="54"
      viewBox="0 0 24 24"
    >
      <rect
        x="2.2"
        y="2.2"
        width="19.6"
        height="19.6"
        rx="5.2"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.8"
      />

      <circle
        cx="12"
        cy="12"
        r="4.2"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.8"
      />

      <circle
        cx="17.5"
        cy="6.5"
        r="1.25"
        fill="currentColor"
      />
    </svg>
  );
}

/* ========================================= */
/* MAIN INSTAGRAM CARD                       */
/* ========================================= */

export async function generateInstagramJobCard(
  job: SocialJob,
): Promise<ArrayBuffer> {
  /*
   * Convert the local illustration into a Base64
   * data URL before creating ImageResponse.
   */
  const illustration =
    getIllustrationDataUrl();

  /* ========================================= */
  /* DYNAMIC JOB DATA                          */
  /* ========================================= */

  const title = truncate(
    job.title || "Job Opportunity",
    54,
  );

  const company = truncate(
    job.companyName || "Company",
    36,
  );

  const location =
    truncate(
      getLocation(job),
      42,
    ) || "Location not specified";

  const experience = truncate(
    getExperience(job),
    24,
  );

  const workMode = truncate(
    job.workMode || "",
    18,
  );

  const employmentType =
    truncate(
      job.employmentType || "",
      18,
    );

  const skills = getSkills(job);

  /* ========================================= */
  /* IMAGE RESPONSE                            */
  /* ========================================= */

  return new ImageResponse(
    (
      <div
        style={{
          width: "1080px",
          height: "1200px",

          display: "flex",
          flexDirection: "column",

          position: "relative",
          overflow: "hidden",

          padding:
            "34px 48px 42px",

          background:
            "linear-gradient(145deg, #FFFFFF 0%, #F9FBFF 60%, #F0F6FF 100%)",

          color: NAVY,

          fontFamily:
            "Arial, Helvetica, sans-serif",
        }}
      >
        {/* ================================= */}
        {/* HEADER                             */}
        {/* ================================= */}

        <div
          style={{
            display: "flex",
            alignItems: "center",
            height: 72,
          }}
        >
          {/* Logo */}
          <div
            style={{
              display: "flex",

              width: 56,
              height: 56,

              borderRadius: 16,

              background:
                "linear-gradient(135deg,#173B78,#1769AA)",

              color: "#FFFFFF",

              alignItems: "center",
              justifyContent: "center",

              fontSize: 34,
              fontWeight: 900,

              marginRight: 14,
            }}
          >
            C
          </div>

          {/* Brand */}
          <div
            style={{
              display: "flex",

              fontSize: 34,

              letterSpacing:
                "-1.4px",

              fontWeight: 500,

              color: NAVY,
            }}
          >
            CareerDiscover

            <span
              style={{
                color: RED,
                fontWeight: 600,
              }}
            >
              Jobs
            </span>
          </div>
        </div>

        {/* ================================= */}
        {/* HERO                               */}
        {/* ================================= */}

        <div
          style={{
            display: "flex",

            height: 330,

            alignItems: "center",

            justifyContent:
              "space-between",
          }}
        >
          {/* ================================= */}
          {/* URGENT HIRING                      */}
          {/* ================================= */}

          <div
            style={{
              display: "flex",

              flexDirection:
                "column",

              width: 500,

              flexShrink: 0,

              paddingLeft: 4,
            }}
          >
            {/* URGENT */}
            <div
              style={{
                display: "flex",

                fontSize: 91,

                lineHeight: 0.91,

                letterSpacing:
                  "-4px",

                fontWeight: 900,

                color: NAVY,
              }}
            >
              URGENT
            </div>

            {/* HIRING */}
            <div
              style={{
                display: "flex",

                marginTop: 4,

                marginLeft: 200,

                fontSize: 91,

                lineHeight: 0.91,

                letterSpacing:
                  "-4px",

                fontWeight: 900,

                color: RED,
              }}
            >
              HIRING!
            </div>

            {/* Red underline */}
            <div
              style={{
                display: "flex",

                width: 350,
                height: 6,

                marginTop: 24,

                marginLeft: 150,

                borderRadius: 999,

                background: RED,
              }}
            />
          </div>

          {/* ================================= */}
          {/* LAPTOP ILLUSTRATION                */}
          {/* ================================= */}

          <div
            style={{
              display: "flex",

              width: 500,
              height: 400,

              alignItems:
                "center",

              justifyContent:
                "center",

              overflow: "hidden",
            }}
          >
            <img
              src={illustration}
              width="500"
              height="400"
              alt="Software testing and QA illustration"
              style={{
                width: 500,
                height: 400,

                objectFit:
                  "contain",
              }}
            />
          </div>
        </div>

        {/* ================================= */}
        {/* JOB TITLE                          */}
        {/* ================================= */}

        <div
          style={{
            display: "flex",

            borderRadius: 10,
            marginTop:40,
            marginBottom:40,

            background: NAVY,

            color: "#FFFFFF",

            padding:
              "22px 26px",

            alignItems:
              "center",

            fontSize:
              title.length > 42
                ? 42
                : 48,

            lineHeight: 1.05,

            fontWeight: 500,

            letterSpacing:
              "-1px",
          }}
        >
          {title}
        </div>

        {/* ================================= */}
        {/* COMPANY + LOCATION + EXPERIENCE    */}
        {/* ================================= */}

        <div
          style={{
            display: "flex",
            marginTop: 14,
            minHeight: 138,
            alignItems:
              "center",
          }}
        >
          {/* COMPANY */}
          <div
            style={{
              display: "flex",

              fontSize:
                company.length > 15
                  ? 58
                  : 76,

              lineHeight: 0.95,

              fontWeight: 900,

              color: RED,

              letterSpacing:
                "-2px",

              alignItems:
                "center",
            }}
          >
            {company}
          </div>

          {/* Divider */}
          <div
            style={{
              display: "flex",

              width: 2,

              height: 105,

              background:
                "#B9C9DE",

              margin:
                "0 25px",
            }}
          />

          {/* Location + Experience */}
          <div
            style={{
              display: "flex",

              flexDirection:
                "column",

              flex: 1,

              gap: 10,
            }}
          >
            {/* LOCATION */}
            <div
              style={{
                display: "flex",

                alignItems:
                  "center",

                color: RED,

                fontSize: 25,

                fontWeight: 500,
              }}
            >
              <LocationIcon />

              <span
                style={{
                  display: "flex",

                  marginLeft: 10,
                }}
              >
                {location}
              </span>
            </div>

            {/* EXPERIENCE */}
            <div
              style={{
                display: "flex",

                alignItems:
                  "center",

                color: NAVY,

                fontSize: 25,

                fontWeight: 500,
              }}
            >
              <BriefcaseIcon />

              <span
                style={{
                  display: "flex",

                  marginLeft: 10,
                }}
              >
                {experience}
              </span>
            </div>

            {/* WORK MODE + EMPLOYMENT */}
            <div
              style={{
                display: "flex",

                gap: 10,
              }}
            >
              {workMode && (
                <div
                  style={{
                    display: "flex",

                    padding:
                      "7px 16px",

                    borderRadius:
                      999,

                    background:
                      "#FFF0F2",

                    border:
                      "1px solid #F6C2C7",

                    color: RED,

                    fontSize: 17,

                    fontWeight: 500,
                  }}
                >
                  {workMode}
                </div>
              )}

              {employmentType && (
                <div
                  style={{
                    display: "flex",

                    padding:
                      "7px 16px",

                    borderRadius:
                      999,

                    background:
                      LIGHT_BLUE,

                    border:
                      "1px solid #C3D7F0",

                    color: NAVY,

                    fontSize: 17,

                    fontWeight: 500,
                  }}
                >
                  {employmentType}
                </div>
              )}
            </div>
          </div>
        </div>

        {/* ================================= */}
        {/* SKILLS                             */}
        {/* ================================= */}

        {skills.length > 0 && (
          <div
            style={{
              display: "flex",
              marginTop:50,

              background:
                "rgba(255,255,255,.9)",

              alignItems:
                "center",

              justifyContent:
                "space-around",

              overflow:
                "hidden",
            }}
          >
            {skills.map(
              (skill, index) => (
                <div
                  key={`${skill}-${index}`}
                  style={{
                    display: "flex",

                    flex: 1,

                    height: 74,

                    alignItems:
                      "center",

                    justifyContent:
                      "center",

                    borderRight:
                      index <
                      skills.length - 1
                        ? "1px solid #C8D4E5"
                        : "none",

                    padding:
                      "0 8px",

                    textAlign:
                      "center",

                    fontSize:
                      skill.length > 17
                        ? 18
                        : 23,

                    lineHeight: 1.1,

                    fontWeight: 200,

                    color:
                      "#172033",
                  }}
                >
                  {truncate(
                    skill,
                    22,
                  )}
                </div>
              ),
            )}
          </div>
        )}

        {/* ================================= */}
        {/* FOOTER CTA                         */}
        {/* ================================= */}

        <div
          style={{
            display: "flex",

            marginTop: "auto",

            height: 226,

            border:
              `1px solid ${BORDER}`,

            borderRadius: 10,

            background:
              "#FFFFFF",

            padding:
              "20px 24px",

            alignItems:
              "center",
          }}
        >
          {/* LEFT CTA */}
          <div
            style={{
              display: "flex",

              flexDirection:
                "column",

              width: 505,

              gap: 13,
            }}
          >
            {/* VIEW DETAILS */}
            <div
              style={{
                display: "flex",

                height: 72,

                borderRadius: 999,

                background: NAVY,

                color: "#FFFFFF",

                alignItems:
                  "center",

                justifyContent:
                  "center",

                fontSize: 23,

                fontWeight: 800,
              }}
            >
              <EyeIcon />

              <span
                style={{
                  display: "flex",

                  marginLeft: 11,
                }}
              >
                VIEW FULL JOB DETAILS
              </span>
            </div>

            {/* APPLY NOW */}
            <div
              style={{
                display: "flex",

                height: 72,

                borderRadius: 999,

                background: RED,

                color: "#FFFFFF",

                alignItems:
                  "center",

                justifyContent:
                  "center",

                fontSize: 26,

                fontWeight: 900,
              }}
            >
              <ArrowIcon />

              <span
                style={{
                  display: "flex",

                  marginLeft: 11,
                }}
              >
                APPLY NOW
              </span>
            </div>
          </div>

          {/* DIVIDER */}
          <div
            style={{
              display: "flex",

              width: 2,

              height: 175,

              background:
                "#C8D4E5",

              margin:
                "0 30px",
            }}
          />

          {/* INSTAGRAM */}
          <div
            style={{
              display: "flex",

              flex: 1,

              flexDirection:
                "column",

              alignItems:
                "center",

              justifyContent:
                "center",
            }}
          >
            <div
              style={{
                display: "flex",

                fontSize: 34,

                fontWeight: 900,

                letterSpacing:
                  "1px",

                color: NAVY,
              }}
            >
              LINK IN BIO
            </div>

            <div
              style={{
                display: "flex",

                marginTop: 12,

                alignItems:
                  "center",

                color:
                  "#D62976",
              }}
            >
              <InstagramIcon />

              <span
                style={{
                  display: "flex",

                  marginLeft: 10,

                  fontSize: 23,

                  fontWeight: 800,

                  color: NAVY,
                }}
              >
                careerdiscoverjobs
              </span>
            </div>
          </div>
        </div>
      </div>
    ),
    {
      width: 1080,
      height: 1350,
    },
  ).arrayBuffer();
}